### ISSUE TITLE
Inspect WalletConnect Kits

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#194]
#### Objective
Assess the ease of accessing contact information for users who log in with social accounts and determine if users can access the private key of the auto-generated account using the Connect Wallet App Kit plugin.

#### Scope
1. **Access to Contact Information:**
   - Investigate how the plugin handles login via social accounts.
   - Evaluate the process and ease of accessing user contact information (e.g., email, name) after login.

2. **Private Key Access:**
   - Determine if the plugin allows users to access the private key of their auto-generated account.
   - Assess the security implications and user experience related to accessing the private key.

#### Deliverables
1. **Testing and Evaluation:**
   - Implement a test setup to evaluate the plugin's functionalities.
   - Document or share the steps and outcomes of accessing contact information and private keys.

2. **Report:**
   - Provide a report on the ease of accessing user contact information.
   - Outline the method for users to access their private keys and any associated security concerns.

### Conclusion
This task aims to evaluate the Connect Wallet App Kit plugin's capabilities regarding social login contact information access and private key management to ensure it meets our requirements and security standards.

**Comment by nomadbitcoin** [comment]
Here is the use case https://peanut.to/

**Comment by andersonlthome** [comment]
Hi, until then, I had success with the Connect Wallet App Kit in a test Nextjs Project, on the client side, where I can get the email used to social login in the localstorage. To work with it, we have a strong adaption of the code, to work in this info in client side.

Get data of wallet generated on login:

![Image](https://github.com/user-attachments/assets/3aa580cf-1268-4a94-99a9-01c3505904b0)


Get data of social login:

![Image](https://github.com/user-attachments/assets/b3cba39b-f48e-482c-a413-e1faf8244f7c)

Studie repo:
https://github.com/andersonlthome/studie-app-kit-wallet-connect
