### ISSUE TITLE
Implement Layout for Task Marketplace

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#195]
**Objective**: Implement the visual design and layout for the [task marketplace](https://www.figma.com/board/27S5enxUJePGwjADVJ6rNT/WEB3TASK-v2-Roadmap?node-id=103-228&t=aYztR6CkpXtKASrM-1) as specified in the provided design mockup. This task focuses solely on the frontend layout.

**Requirements**:
- [x] **Filters Section**: Implement the filter panel with checkboxes for Skill, Context Depth, Reward.
- [x] **Tasks Listing**: Create task cards displaying name, description, skills, languages, and rewards.
- [x] **Sorting Functionality**: Include a dropdown to sort tasks by 'Context Depth' and 'Reward'.
- [x] **Responsive Design**: Ensure the layout is responsive across devices.
- [ ] **Accessibility**: Make all elements accessible with keyboard and screen reader support.

**Deliverables**:
- [x] Implement the frontend layout in HTML/CSS.
- [ ] Ensure integration with backend functionalities.

**Comment by Hardsys-Andre** [comment]
Hi @nomadbitcoin , task completed.
PR made to anásile so that @Guboehm  can integrate with backend related to task filter.
follow the PR link: https://github.com/w3b3d3v/web3-bootcamp-platform/pull/196

**Comment by nomadbitcoin** [comment]
Closed at PR #196
