### ISSUE TITLE
SortBar Should work for any metadata. Such as from Builds and StudyGroups

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#201]
Could this be a individual component to be reused such as Filter and Search?

_Originally posted by @nomadbitcoin in https://github.com/w3b3d3v/web3-bootcamp-platform/pull/196#discussion_r1697623479_

**Comment by viniblack** [comment]
[PR](https://github.com/w3b3d3v/web3-bootcamp-platform/pull/244)
