### ISSUE TITLE
User-Specific Task Visibility

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#205]
- [x] Implement logic to show tasks based on the user’s level of context.
- [x] Apply shadow effects to tasks that are not available for the specific user.

**Comment by nomadbitcoin** [comment]
Shadow example:

![Image](https://github.com/user-attachments/assets/46d9c70e-1a96-42de-b09d-e3d5ab3792fa)

**Comment by viniblack** [comment]
I'm interested

**Comment by viniblack** [comment]
https://github.com/w3b3d3v/web3-bootcamp-platform/pull/229

**Comment by viniblack** [comment]
It will be resolved in this [PR](https://github.com/w3b3d3v/web3-bootcamp-platform/pull/237)
