### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#207]
We need to finalize the configuration and refinement of the testing environment for our project to ensure that all functionalities and UI components work as expected. Significant progress has been made in fixing broken tests, but additional steps are required to complete the setup. The tasks completed and remaining are outlined below:

### Completed Tasks:
- [x] Fix broken tests.
  - [x] ThemeSwitch tests
  - [x] Tabs tests
  - [x] Login tests
  - [x] Social data tests
  - [x] Lessons and sections tests
  - [x] General info tests
  - [x] Profile footer tests
  - [x] Professional data warnings
  - [x] Personal data tests

**Comment by viniblack** [comment]
i can do this task

**Comment by viniblack** [comment]
running the tests already existing in the project:
`components/Button/index.spec.js` - (08/08)
`components/Card/index.spec.js` - (07/07)
`components/Card/GeneralInfo/index.spec.js` - (00/02)
`components/Card/GeneralInfo/PersonalData/index.spec.js` - (00/05)
`components/Card/GeneralInfo/ProfileFooter/index.spec.js` - (01/04)
`components/Card/GeneralInfo/ProfileProgress/index.spec.js` - (03/03)
`components/Card/GeneralInfo/SocialData/index.spec.js` - (00/03)
`components/Footer/index.spec.js` - (00/03)
`components/ThemeSwitch/index.spec.js` - (00/01)
`pages-test/auth/login.spec.js` - (02/04)
`pages-test/signup/login.spec.js` - (02/04)

**Comment by viniblack** [comment]
Most tests are failing because of `useSession` of the `DiscordCard` component

![img](https://cdn.discordapp.com/attachments/1018684397265883216/1271170572209881139/image.png?ex=66b7aed9&is=66b65d59&hm=f1fa6f69fb06427e715a36d01a5d9ef3c89c0c1d01325cd36a5c6c948f5411a6&)

**Comment by viniblack** [comment]
[PR](https://github.com/w3b3d3v/web3-bootcamp-platform/pull/222) created for the following tests:
`components/Footer/index.spec.js`
`components/ThemeSwitch/index.spec.js`
`pages-test/auth/login.spec.js`
`pages-test/signup/login.spec.js`
