### ISSUE TITLE
FIX: Application crashes when mouse hovers over fields in task card

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#214]
Task metadata should work dynamically but it is currently expecting some fields to be present.

**Comment by nomadbitcoin** [comment]
![Image](https://github.com/user-attachments/assets/db357301-314f-4913-8246-170495256534)

**Comment by nomadbitcoin** [comment]
![Image](https://github.com/user-attachments/assets/cc255aa9-334f-40ae-b081-ee0aee4c89e4)

**Comment by Guboehm** [comment]
@nomadbitcoin problem fixed in filter pr, close this issue please
