### ISSUE TITLE
Apply Button -> Github Integration

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#217]
When a user clicks "Apply," the following actions should take place:

**Check GitHub Connection:**
  - [ ] Verify if the user has connected their GitHub account.
    - [ ] If not, redirect them to the GitHub connection URL.

**Comment by Hardsys-Andre** [comment]
@nomadbitcoin and @Guboehm, follow PR for verification:
Link: https://github.com/w3b3d3v/web3-bootcamp-platform/pull/234
