### ISSUE TITLE
Task description with Markdown

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#230]
We're aiming to enhance the Task card component with the following updates:

1. **Image Display:** 
   - Ensure that the image is properly displayed and aligned on the Task card.

2. **Description Formatting:**
   - Implement `react-markdown` to render the task description, allowing for rich text formatting.

3. **Short Description View:**
   - Introduce a "Short Description" field on the Task card. This will provide a brief overview of the task.
   - When the user clicks on the task, expand the view to reveal the full description.

![Task Card Image](https://github.com/user-attachments/assets/e4718244-68b1-4c06-9891-ce6a76f39d12)

**Comment by viniblack** [comment]
I thought we'd follow onlydust's example, leave the title and to see the task description you need to click on see more.

![Image](https://github.com/user-attachments/assets/e6049471-6888-48cb-b7ee-4c1172ce3ee9)



![Image](https://github.com/user-attachments/assets/94a58f79-c844-47b5-878c-c5e40094f6d0)

**Comment by viniblack** [comment]
https://github.com/user-attachments/assets/aba2f20d-259f-4f7a-acf5-d16db8643fef

**Comment by viniblack** [comment]
[PR](https://github.com/w3b3d3v/web3-bootcamp-platform/pull/237)
