### ISSUE TITLE
Create Tests for validate Sign-in/Signup

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/web3-bootcamp-platform#258]
# Description:

Develop automated tests to validate the functionality of the Sign-in and Signup processes on the platform, ensuring a smooth and error-free user experience.

**Tasks:**
1. - [x] Create automated tests for the Sign-in process, covering various scenarios
(e.g., valid credentials, invalid credentials, password reset).
2. - [x] Create automated tests for the Signup process, including scenarios like new user registration, form validation ~and duplicate email checks~
3. - [ ] ~Validate the tests on multiple devices and browsers to ensure compatibility.~
4. - [x] Document the testing process and include instructions for running the tests.
5. - [ ] Fix any issues or bugs identified during the testing process.
6. - [ ] Share test results with the development team and implement improvements if necessary.

**Comment by viniblack** [comment]
[PR-Create Tests for validate Sign-in/Signup](https://github.com/w3b3d3v/web3-bootcamp-platform/pull/262)
